const ADD_TRANSACTION = 'ADD_TRANSACTION';
const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

export {
  ADD_TRANSACTION,
  EDIT_TRANSACTION,
  REMOVE_TRANSACTION
};