const TOGGLE_ADD_TRANSACTION_MODAL = 'TOGGLE_ADD_TRANSACTION_MODAL';
const TOGGLE_TRANSACTION_REMOVE_CONFIRM = 'TOGGLE_TRANSACTION_REMOVE_CONFIRM';
const ADD_TRANSACTION = 'ADD_TRANSACTION';
const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

export {
  TOGGLE_ADD_TRANSACTION_MODAL,
  ADD_TRANSACTION,
  EDIT_TRANSACTION,
  TOGGLE_TRANSACTION_REMOVE_CONFIRM,
  REMOVE_TRANSACTION
};